"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var chars = require("./classes/chars");
var weapon = require("./classes/weapons");
var armors = require("./classes/armors");
var fight_1 = require("./classes/fight");
var buffs = require("./buffs/buffs");
var mage1 = new chars.Mage('MagicWave', 7);
mage1.setWeapon(new weapon.magicStuff());
mage1.setArmor(new armors.Robe());
var warrior1 = new chars.Warrior('DarkKnight', 5);
warrior1.setWeapon(new weapon.Axe());
warrior1.setArmor(new armors.heavyArmor());
var archer1 = new chars.Archer('ArrowHurrican', 5);
archer1.setWeapon(new weapon.Bow());
archer1.setArmor(new armors.lightArmor());
archer1.setBuff(new buffs.berserk());
var priest1 = new chars.Priest('Saint', 11);
priest1.setWeapon(new weapon.priestSoul());
priest1.setArmor(new armors.Robe());
var fight = new fight_1.Fight(warrior1, archer1);
fight.start();
